database: bigquery # {bigquery, snowflake}
bucket: # {name of bucket}

spark:
    spark.driver.memory: 16g
    spark.jars: [spark-bigquery-latest_2.12.jar, gcs-connector-hadoop3-latest.jar] # jars needed for provider, gcp 
    spark.jars.packages: [com.johnsnowlabs.nlp:spark-nlp_2.12:5.2.0] # include packages from ivy
    # spark.hadoop.google.cloud.auth.service.account.enable: # use service account?
    # spark.hadoop.google.cloud.auth.service.account.json.keyfile: 
    fs.gs.impl: com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem # hadoop fs
    spark.sql.execution.arrow.pyspark.enabled: true # use arrow
    spark.driver.extraJavaOptions: -Dlog4j.configuration=file:/home/ryeyoo/projects/spark-loader/conf/log4j.properties
    spark.executor.extraJavaOptions: -Dlog4j.configuration=file:/home/ryeyoo/projects/spark-loader/conf/log4j.properties

bigquery:
    viewsEnabled: true
    parentProject: # write project
    materializationDataset: # write dataset

