database: bigquery
bucket: bigquery-tmp-bucket

spark:
    spark.driver.memory: 16g
    spark.jars: [spark-bigquery-latest_2.12.jar, gcs-connector-hadoop3-latest.jar]
    spark.hadoop.google.cloud.auth.service.account.enable: true
    spark.hadoop.google.cloud.auth.service.account.json.keyfile:
    fs.gs.impl: com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
    spark.sql.execution.arrow.pyspark.enabled: true

bigquery:
    viewsEnabled: true
    parentProject: prod
    materializationDataset: temp_staging

